[phases.setup]
nixPkgs = ["nodejs_22", "npm-11_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[variables]
NODE_ENV = "production"

[start]
cmd = "node build/index.js"
